### ISSUE TITLE
Feat: Pings for leveling up should be enabled above level 40 or 50

### ISSUE THREAD

**Issue by isaaccommits** [IIoW/IIslander#149]
### Is your feature request related to a problem? Please describe.

Removing pings for early leveling was a good choice, but I don't feel like it should be removed altogether. Getting pinged for reaching higher levels is nice, as you can know when you've hit a milestone easier and prevent missing them altogether

### Describe the solution you'd like

Make level-up messages start pinging upon reaching level 40 or 50

### Describe alternatives you've considered

A lower or higher number would be ok too

**Comment by KommentatorForAll** [comment]
we (chicken) thinks it would be better done with a command instead of hardcoding the level, which might seem random to the users.
if you want to check it out, look at the pr #148
