### ISSUE TITLE
Award messages should ping the awarded user

### ISSUE THREAD

**Issue by isaaccommits** [IIoW/IIslander#153]
### Is your feature request related to a problem? Please describe.

I'd like to see when I'm awarded easier, as it's nice to get awards and fun to look at what you've been awarded for.

### Describe the solution you'd like

Pings for getting awarded.

### Describe alternatives you've considered

Not pinging for bronze awards, or perhaps another user toggle command thingy

**Comment by WilsontheWolf** [comment]
I wonder if we could tie this to the level up ping or would you rather not?

**Comment by isaaccommits** [comment]
It could be tied to the level up, yeah
