### ISSUE TITLE
Bug: no screening

### ISSUE THREAD

**Issue by KommentatorForAll** [IIoW/IIslander#259]
### Describe the bug

there is no screening for new members, because we immediately apply roles to them, therefore automatically skipping the member screening. This allowes easier access for bots into the server and other fake spam accounts

### Steps to reproduce

join the server 

### Expected behavior

member get screened and have to interact with something

**Comment by KommentatorForAll** [comment]
member.pending exists, true while not finished screening, emits a onGuildMemberUpdate when done screening.

**Comment by KommentatorForAll** [comment]
probably gonna implement on wednesday

**Comment by WilsontheWolf** [comment]
It should be as simle as just moving the join code related to roles, to the guildMemberUpdate event and only run if pending.

**Comment by WilsontheWolf** [comment]
I would also consider this a feature/enhancment, as its not something wrong with our code, but implementing something new

**Comment by WilsontheWolf** [comment]
Fixed in #260
